### ISSUE TITLE
Create an official #learnjavascript track

### ISSUE THREAD

**Issue by danecando** [learn-javascript/learn-javascript.github.io#9]
We can decide on an official track to include on the page

**Comment by robotmayo** [comment]
It should be similar to the JSISEXY one with resources, a bit of tutorial and some projects. Newbies love projects. I think we can define the projects better, JSISEXY tends to be a bit weak when it comes to describing the task.

**Comment by danecando** [comment]
Makes sense to me. Nothing like putting what you're learning into practical application. So will there be any books in track? Is it laid out in some sort of timeframe?

**Comment by jarofghosts** [comment]
my concern is around who is maintaining this

**Comment by danecando** [comment]
I figured it would be a #learnjavascript colab. We could just gussy it up a bit and just keep it as a list of resources (my original intention). The only reason I originally asked was because I wanted to know if I could add resources to the list or if it was something that was set in stone.

**Comment by olivierrr** [comment]
:+1:

**Comment by Roilan** [comment]
Would adding paid services be acceptable?

**Comment by danecando** [comment]
Join the gang putting together our JavaScript track / resources @ https://trello.com/b/LTCUlQ3T/learnjavascript
